### ISSUE TITLE
MalformedInputException when downloading exported files

### ISSUE THREAD

**Issue by cseppan** [USEPA/emf#146]
Originally reported by Charlie on Thursday, January 11, 2024 4:05 PM

![image002](https://github.com/USEPA/emf/assets/7329179/c83bbd6a-3a1f-4106-a57b-88ffc5d9bcfa)

> I was exporting the inventories from an old control strategy because I need to add some information to the strategy results. So, yes, just a regular dataset export.
 
> Some of the files have exported fine, while others gave up and threw that exception. I just tried it a different way by exporting directly from the dataset manager, and it seems to be failing in a different way. It created the blank file in my output directory but does not seem to be populating it. While I had the same thought about the length of the file name, I haven’t tried to change the name because they’re not my files and I wasn’t sure if it would break something. And the fact that it was able to create the blank file in my output directory makes me wonder if something else is happening. I think the files that are failing are making it to the export directory on the server, but then aren’t making it to my computer.

Alison tried to export and download the same file, which also failed:

![image001](https://github.com/USEPA/emf/assets/7329179/2d0e3249-7dde-44a3-8c87-61970fcd4b58)

**Comment by ddelvecchio** [comment]
Changed over from using a CharConsumer approach to a BinaryConsumer approach, this approach is not as dependent on the character encoding scheme.

**Comment by cseppan** [comment]
Code updates in commit e4b80bc. Released in EMF v4.3
